<?php

namespace Form\FormBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SiteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Form\FormBundle\Controller\SiteController();
        return $instance;
    }
}
