parameters:
#    form_form.example.class: Form\FormBundle\Example

services:
#    form_form.example:
#        class: %form_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
